version: '3.7'
services:
   zookeeper-1:
      extends:
         file: ../common/docker-compose.yml
         service: zookeeper-1
      volumes:
      - ./data/zk/data:/var/lib/zookeeper/data
      - ./data/zk/logs:/var/lib/zookeeper/log
   kafka-1:
      extends:
         file: ../common/docker-compose.yml
         service: kafka-1
      depends_on:
      - zookeeper-1
      volumes:
      - ./data/kafka/data:/var/lib/kafka/data
   zipkin:
      extends:
         file: ../common/docker-compose.yml
         service: zipkin
      depends_on:
      - zookeeper-1
      - kafka-1