server:
  port: 8070
logging:
  level:
    root: info
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
resilience4j:
  # https://resilience4j.readme.io/docs/circuitbreaker
  circuitbreaker:
    instances:
      employee-management:
        failure-rate-threshold: 60
        slow-call-duration-threshold: 1000        
  retry:
    instances:
      employee-management:
        max-attempts: 3
        wait-duration:
          seconds: 1
        enable-exponential-backoff: true